version: '3.8'

services:
  # RabbitMQ 서비스
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin123
    ports:
      - "5672:5672"   # AMQP
      - "15672:15672" # Management
      - "61613:61613" # STOMP
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - chattingrabbit-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Backend 서비스
  backend:
    build: ./backend
    container_name: chattingrabbit-backend
    environment:
      # Spring Boot 프로필
      - SPRING_PROFILES_ACTIVE=docker
      
      # 서버 설정
      - SERVER_PORT=8080
      
      # RabbitMQ 설정
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=admin
      - RABBITMQ_PASSWORD=admin123
      - RABBITMQ_VHOST=/
      
      # STOMP 설정
      - STOMP_HOST=rabbitmq
      - STOMP_PORT=61613
      - STOMP_LOGIN=admin
      - STOMP_PASSCODE=admin123
      
      # CORS 설정
      - CORS_ALLOWED_ORIGINS=http://localhost:80,http://localhost:3000
      
      # 로깅 설정
      - LOG_LEVEL_APP=DEBUG
      - LOG_LEVEL_WEB=DEBUG
      - LOG_LEVEL_AMQP=DEBUG
    ports:
      - "18080:8080"
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - chattingrabbit-network
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8080/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend 서비스
  frontend:
    build: ./frontend
    container_name: chattingrabbit-frontend
    environment:
      # Frontend 설정
      - VITE_API_BASE_URL=http://localhost
      - VITE_WS_BASE_URL=http://localhost
      - VITE_FRONTEND_PORT=80
      - VITE_DOCKER_ENV=true
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - chattingrabbit-network
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:80 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

# 네트워크 정의
networks:
  chattingrabbit-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

# 볼륨 정의
volumes:
  rabbitmq_data:
    driver: local
